package ui;

public enum EnumInfluencerButtonProperty {
    AGE_UP,
    AGE_DOWN,
    APPEARANCE_NEXT,
    APPEARANCE_PREV,
    CHANGE_MALE,
    CHANGE_FEMALE,
    RANDOMIZE_NAME,
    RANDOMIZE_APPEARANCE,
    NEXT_TRIBE,
    PREVIOUS_TRIBE,
    RANDOMIZE_TRIBE,
    NEXT_VOICE,
    PREVIOUS_VOICE,
    RANDOMIZE_VOICE;


}
